##Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [24]:
l2=[]
def movavg(l1,win):
    for j in range(len(l1)-win+1):
        i=j
        avg=0
        #print(j)
        
        for i in range(j, win+j):
            
            
            avg+=l1[i]
        #print(avg)
        l2.append(avg//3)
        
    return l2 
l1=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
win=3
res=[]
res=movavg(l1,3)
print(len(res))

11


In [25]:
import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [26]:
import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix1 = np.vander(x,N,increasing=False)
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [27]:
np.linalg.det(matrix)

287.9999999999977

In [28]:
np.linalg.det(matrix1)


287.9999999999977